server:
  port: 8761
  servlet:
    context-path: /eureka-server
spring:
  application:
    name: discovery-service

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  instance:
    hostname: localhost